### ISSUE TITLE
[Reverse Proxy with Path] Nginx Proxy at path /xxx  - Results "Loading Sshwifty"

### ISSUE THREAD

**Issue by kalzi** [niruix/sshwifty#10]
Hello There, 

I would like to seek your advise on how to setup sshwifty behind a Reverse Proxy.. I am using Ngnix as a proxy and when i try to proxy the sshwifty app at location / - everything works.

```
location / {
		proxy_pass http://172.17.0.3:8182;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $http_host;
		proxy_set_header X-NginX-Proxy true;
        }
    }
```

But when I move the config to be served under path /sshclient, then loading of `manifest.json` and `css` files seem to be broken

```
location /sshclient/ {
		proxy_pass http://172.17.0.3:8182;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $http_host;
		proxy_set_header X-NginX-Proxy true;
        }
    }
```

Attempting to access the url/sshclient results in "× Server was unable to complete the request"

Modifying the config to 

```
    location /sshclient/ {
                rewrite ^/sshclient(.*) $1 break;
                proxy_ignore_client_abort on;
		proxy_pass http://172.17.0.3:8182;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $http_host;
		proxy_set_header X-NginX-Proxy true;
        }
```

with above change and i browse to http://uri/sshclient i see following
```
Loading Sshwifty
Client is currently being loaded. Should only take a few seconds, please wait

Copyright © 2019 Rui NI <nirui@gmx.com>

Source code Readme License
```
When i attempted to debug using chrome developer tools, i notice the following

```
GET http://localhost/manifest.json 404 (Not Found)
GET http://localhost/6218340eaf037830067c.css net::ERR_ABORTED 404 (Not Found)
```

While i am not an expert at web developer or belong to a developer profile, i suspect that this is an issue with static files that are failing to be served.. 

Any advise?

**Comment by niruix** [comment]
Hello, currently it is impossible to map Sshwifty to a sub directory. Sorry.

The reason behind this design is complicated. Mainly because this application require a clean [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) space which is used to store the "Known remotes" data.
 
Putting the application under a subdirectory cannot  guarantee that as some other application may accidentally modify or delete that data.

Can you use sub *domain* (for example `sshclient.yourdomain.tld`) rather than directory?

**Comment by kalzi** [comment]
Thanks for clarifying this Rui. Will attempt to host at Root URI. 

Will keep watch towards stable release. Thanks again for sharing.

**Comment by niruix** [comment]
> Thanks for clarifying this Rui. Will attempt to host at Root URI.
> 
> Will keep watch towards stable release. Thanks again for sharing.

I'm glad you like this software :)

Also, just letting you know that I'm working on a *trick* that allowing sysadmin to *fake* the sub-directory mapping by taking advantage of `rewrite` and `redirect` feature of some HTTP reverse proxy server.

The original problem which blocking sysadmin from doing sub-directory mapping is very simple: Sshwifty assets (including the landing page etc) are all statically generated, and always bound to the root url `/`.

When Sshwifty is mapped to a sub-directory (`/sshclient` for example), web browser will still be asked by the landing page to download assets from `/` (For example, `/manifest.json` rather than `/sshclient/manifest.json`), which of course will fail.

To walk around that problem while keeping everything statically generated, I moved the assets path from `/` to `/sshwifty/assets`, and moved websocket interface from `/socket` to `/sshwifty/socket`. This way, sysadmin can redirect those requests based on URL path prefixes.

Of course this is not a perfect solution, as all assets are still hard-pointed to `/sshwifty/*`, but at least it enables sysadmin to map Sshwifty to a sub-directory rather than having to setup multiple domains.

I already implemented the idea in 2356a7c1552e67178a0553888beed29164e0331a, and tested it with following configuration:

```
events{
    worker_connections 1024;
}

http{
    index index.html index.html;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    upstream websocket {
        # Up Stream Websocket server, change address accordingly
        server 10.220.179.110:8182;
    }

    server{
        listen 80;
        server_name localhost;

        location = /sshwifty/socket {
            # Proxy to the websocket interface, change address accordingly
	    proxy_pass http://10.220.179.110:8182/sshwifty/socket;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

        location /sshwifty/ {
            rewrite ^/sshwifty/assets/(.*) /sshwifty/assets/$1 break;
            rewrite ^/sshwifty/(.*) /$1 break;

            # Proxy to the landing page, change address accordingly
	    proxy_pass http://10.220.179.110:8182;
        }
    }
}
```

The configuration above will map Sshwifty to `/sshwifty`. If you instead want to use `/sshclient` however, then you need to redirect `/sshwifty` to `/sshclient/sshwifty`:

```
events{
    worker_connections 1024;
}

http{
    index index.html index.html;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    upstream websocket {
        # Up Stream Websocket server, change address accordingly
        server 10.220.179.110:8182;
    }

    server{
        listen 80;
        server_name localhost;

        location = /sshwifty/socket {
            # Proxy to the websocket interface, change address accordingly
	    proxy_pass http://10.220.179.110:8182/sshwifty/socket;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

        # Notice you have to redirect the request from /sshwifty/* to /sshclient/sshwifty/*
        location ~ ^/sshwifty/(.*) {
            return 301 /sshclient/sshwifty/$1;
        }

        location /sshclient/ {
            rewrite ^/sshclient/(.*) /$1 break;

            # Proxy to the landing page, change address accordingly
	    proxy_pass http://10.220.179.110:8182;
        }
    }
}
```

The change will be available in the next release (0.1.10-beta-release).

**Comment by kalzi** [comment]
Brilliant!! Thanks for putting some thought on it and applying smart tricks.. I will test it out on my side on 0.1.10-beta and shall let us know how it goes.

**Comment by kalzi** [comment]
I have tested the subdirectory structure on my existing domain and it works flawlessly, all things work as expected

if you may be curious, i see following errors in the Chromve Dev Tools Console.. Suspect these are trivial and can be ignored?

```
/term/sshwifty/assets/manifest.json:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)

/sshwifty/assets/manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.

onloadwff.js:71 Uncaught TypeError: Cannot read property 'type' of undefined
    at setFieldValue (onloadwff.js:71)
    at HTMLFormElement.formKeydownListener (onloadwff.js:71)
```

Thank you for the fix.

**Comment by niruix** [comment]
I'm glad it helped :)

The `manifest.json` is the [Web App Manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest) generated by an automatic process during building, and it won't effect the application itself.

I *guess* the cause of the error is because you've setup a HTTP authorization on your Nginx, thus the 401 error. If that's the case, then yeah, you can safely ignore it if everything else works fine.
