### ISSUE TITLE
[PowerLine Fonts Support] Oh-My-Zsh and Agnoster

### ISSUE THREAD

**Issue by kalzi** [niruix/sshwifty#11]
Hi Rui, 

I am curious if its possible to define Font details like "`Size`", "`Name`" and "`Color`"  and `background` `color` in an environment variable of sort to enable loading PowerLine/Nerd Fonts to support the fancy glyphs.. 

It would be awesome to change/define these elements as we please.. possible?

**Comment by niruix** [comment]
Well, the simple answer is no. It is impossible to add such setting to enable/disable font loading, because Sshwifty client is basically a web page which have no knowledge about which font is available on the client web browser. Also, WebFont format is differ than the TTF.

For now, what I can do is to ship the software with a font that supports PowerLine symbols. The downside is that user is still unable to change which font to use by themselves.

I already have an implementation (19473ae1618dc502de1670106ef893cf1071f225) of the idea, it uses [Hack](https://github.com/source-foundry/Hack) font which is providing limited support for PowerLine (but no support for Nerd font symbols).

In addition to that, I also added two buttons to allow user to adjust text size after they have connected to a terminal. The buttons can be accessed through the Console Toolbar, which can be opened by clicking the Tab Label of currently opened tab.

I already deployed the updated software to the demo service https://sshwifty.herokuapp.com/. Could you give it a try to see if it resolved any of your request?

**Comment by kalzi** [comment]
Working as expected.. Thank you

<img width="1236" alt="Screenshot 2019-12-12 at 11 43 02 PM" src="https://user-images.githubusercontent.com/14212713/70726832-a95ce400-1d39-11ea-80c8-6f4f703d0167.png">

Quick question though, if I were to package/build from your source code, should I just need to replace the "Hack" with powerline font of my choice and ensure that font is installed to my client system..

Font Size change works as you suggested.. lastly any advice on the background color change? I assume it also must go along during the build phase? if yes, what is the section we are to edit?

**Comment by niruix** [comment]
Well, if you REALLY REALLY want to use custom font, then yes, you need to remove all the references to the Hack font in the code, and replace it with font of your own choice. 

*Currently*, the those references are mainly in [screen_console.css](https://github.com/niruix/sshwifty/blob/c018c7b4becbdde5a69a7c3048018abb7d35659b/ui/widgets/screen_console.css#L22) and [screen_console.vue](https://github.com/niruix/sshwifty/blob/c018c7b4becbdde5a69a7c3048018abb7d35659b/ui/widgets/screen_console.vue#L100). But that could change in the future as the dependencies and the software it self gets updated, so you better do a scan to locate all the references before changing it.

As of the background color, they are [randomly generated](https://github.com/niruix/sshwifty/blob/02f14eb14fdff62ed11844b967dd93eaa7849f00/ui/commands/color.js#L75). You can make your own color generator to return a fixed color if you want to, something like:

    {
      get() {
        return {
          color: "#333333",
          dark: "#111111"
        }
      }
    }

And then change [this line](https://github.com/niruix/sshwifty/blob/6fa14fabb45a165943f6225d8d0b2e5036d865f0/ui/app.js#L73) to:

    let uiControlColor = {
      get() {
        return {
          color: "#333333",
          dark: "#111111"
        }
      }
    }

However, I wouldn't recommend those modifications, as some quirk thing might starts to happen afterwards. Also, keep in mind, I maybe unable to provide any help to fix those quirks. So be careful :)

**Comment by kalzi** [comment]
Thanks Rui for the advise, yes I shall refrain from branching out with customisations as that would not help in consuming your best work right out of the release channel.  

Indeed, I like your selection of Roboto and the Background color, but I just got curious if its easy to make changes if at all. I am looking forward for the Hack font to the main release if you plan to push it.

Great work as always.. Very elegant.

**Comment by jeffr1975** [comment]
Hello.  I know this is closed.  Was the Hack font actually implemented?  I am running docker tag sshwifty niruix/sshwifty:0.2.21-beta-release and it is not showing the zsh prompts in the screenshots above but just the block cursor characters.  Thanks in advance.  I really love sshwifty so far.  It solves my needs of having a simple web ssh client!
