### ISSUE TITLE
Request: support for URL arguments/parameters

### ISSUE THREAD

**Issue by mourtesa** [niruix/sshwifty#16]
It will be nice to have, to able to pass arguments by url like following example which opens the session directly within a new browsertab without any prompter:
http://localhost:8022/?hostname=xx&username=yy&password=string_base64_encoded
BR
Max

**Comment by niruix** [comment]
Can you use builtin launcher URL feature instead?

For example: https://sshwifty.herokuapp.com/#+Telnet:towel.blinkenlights.nl

The URL can be generated on the "Known remotes" tab after you have already connected to a remote host: On the host item, click "Copy link", then the URL will be copid into your clipboard.

Of course, Sshwifty will still ask user for input when needed. For example, to enter a password etc.

As for password= , I personally never believed that it is a good idea to share password online, even when the password is encode or/and encrypted. So I won't add that, sorry. :)

**Comment by mourtesa** [comment]
I already using that but this feature makes sense if you have 100s of hosts with sshkeys/pwds coming from db table

**Comment by niruix** [comment]
Sshwifty is designed to be a small online SSH client, a simplified strip down version of Putty if you'll.

It really not prepared to be used as a heavy duty SSH management platform.

I think more powerful software such as  [Guacamole](https://guacamole.apache.org/) is what you needed if you have that amount of machines to manage :)

**Comment by mourtesa** [comment]
thx but I don't use anything implemented using java :) any hints to implement by my own?  never touched vue application :/ otherwise... I will go with https://github.com/huashengdun/webssh

**Comment by niruix** [comment]
Well actually, me kind the same when it comes to Java :D

I know `huashengdun/webssh`, it does provide better integration capabilities while Sshwifty does not (Sshwifty is not designed with integration in mind at all). 

However, since your intention is to manage a large amount of SSH machines, I'd recommend to use a software which been built for that specific purpose for better usability and security. 

I did a little search, and found following softwares that may help you:
- https://github.com/jumpserver/jumpserver (12k stars)
- https://github.com/tp4a/teleport (521 stars)
- https://github.com/libragen/felix (340 stars)

None of that is Java. But sadly, the first two doesn't seems to have English doc at all, you may have to Google Translate them.

**Comment by mourtesa** [comment]
wow! thx for your effort, may be I should start to learn mandarin :) however I still prefer your thin single daemon design without any dependencies, because I already have self developed centralised management backend app and db for the hosts and I also have multiple jumphosts makes it more easier just deploy your deamon and run :)

**Comment by niruix** [comment]
The thing is, Sshwifty is fully optimized for what it is, a small SSH/Telnet web client, and nothing else. Many design decisions has been made to achieve that goal, and some of those decisions also prevents Sshwifty from becoming something else.

For example, Sshwifty always rely on user input to configure the connection, while a safe SSH management platform should do the exact opposite (The user must unable to know some parameters such as password, private key etc).

In order for Sshwifty to do the extra correctly (according to the best practice), a huge portion of the code must be altered which may negatively effecting the existing features. 

Because of that, I don't intent to introduce this feature into Sshwifty, at least in the short term. Sorry :(
