### ISSUE TITLE
Docker Image support for arm64/v8

### ISSUE THREAD

**Issue by ilteoood** [niruix/sshwifty#25]
Hi,
I would like to deploy it to my rpi, which uses arm64/v8.
Can it be possible?

Thanks,
Matteo

**Comment by niruix** [comment]
I don't have the hardware needed to build the image, plus the current build process is already a nightmare for me (It's manual). So I'm afraid this will not happen anytime soon, sorry.

**Comment by ilteoood** [comment]
You don't need the hardware to do it :)
If you want to create multi-arch build, you can use GitHub actions!
Please check an example that I did on an image that I made: https://github.com/ilteoood/docker-surfshark/tree/master/.github/workflows

**Comment by niruix** [comment]
OK, I'll take look the `docker buildx` solution, thanks for the info. 

However ... in order to do that, I then have to switch the build process to use GitHub Action instead of Travis CI, it still take awhile to implement it correctly. I'll keep you posted if there are any updates on this.

Thank you again :)

**Comment by niruix** [comment]
Hello.

Sorry for the long delay, I been busy on many other things recently.

I have made the switch from Travis CI to GitHub Action. As part of that change, the Docker Images of Sshwifty will also be build on GitHub Action instead of Docker Cloud. The result is that, *yes, we have prebuilt `linux/arm64` Docker Image now*. Simply `docker run ..... niruix/sshwifty:latest` as described [here](https://github.com/niruix/sshwifty#docker-image) on an arm64 machine should get things started.

However, I cannot use your GitHub Action mentioned above, because, well, it turns out things are not that easy (You know, wired things happens when QEMU comes to play). I have to make a custom script (`.ci.sh` file) to invoke `docker buildx` manually so nobody suddenly segfaults.
