### ISSUE TITLE
how modify config in docker, and  how can I make the backspace key work properly in telnet?

### ISSUE THREAD

**Issue by hyzeer** [niruix/sshwifty#30]
1) I use docker to run this application, how can i use "SharedKey" a field? 
2) in Telnet, backspace is not valid, Need to use shift+backspace or ctrl+h to achieve the function of backspace. What should I do?

Thanks a lot!

**Comment by niruix** [comment]
Hello there,

For the Docker part, you can do so by setting environment variable `SSHWIFTY_SHAREDKEY` via `--env` option when you start the container.

For the Telnet part however, the story is a bit longer: Sshwifty uses `xtermjs` which is an xterm emulator, it sends `BS` instead of `^H` key when `Backspace` key is pressed.

I can add a keymap feature that allows for key conversion which will resolve the issue. But of course, doing so takes time and I'm kind busy recently.

So, In the meantime, I guess you have to stick with `Ctrl+H` / `Shift+Backspace` hotkey :P

**Comment by hyzeer** [comment]
明白了，感谢答复！
