### ISSUE TITLE
Cannot push to heroku

### ISSUE THREAD

**Issue by nullifye** [niruix/sshwifty#5]
I have already compile the source code on my local computer, but failed on _npm run build_

![1](https://user-images.githubusercontent.com/11532124/65033604-ee11f280-d977-11e9-8f2e-f23c4b644d6c.PNG)

It when well when running command _npm run generate_.

Then i push to heroku using _git push heroku master_, i got this error

**cannot load github.com/niruix/sshwifty/application/controller/static_pages: cannot find module providing package github.com/niruix/sshwifty/application/controller/static_pages**

![2](https://user-images.githubusercontent.com/11532124/65033976-b5bee400-d978-11e9-8bf6-0346360aa09e.PNG)

Can you give me the heads up on how to deploy on heroku.com?

**Comment by niruix** [comment]
The command has failed because Windows doesn't support  `EVN=VAL Command` command line syntax. You can manually run `go generate` and then `go build` to complete the build process.

However, a much simpler way to deploy onto Heroku is to use the [`.heroku.yml`](https://github.com/niruix/sshwifty/blob/master/heroku.yml) file that come with the source code. It uses the [`Dockerfile`](https://github.com/niruix/sshwifty/blob/master/Dockerfile) which contains the entire build process needed to build a Sshwifty Docker image.

Please [read this](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml#getting-started) article to get started (Follow the section "Get started" step 3 and 4 should get you ready).

Keep in mind that after the deployment, you need to manually setup a  config var in the Heroku control panel: Name: `SSHWIFTY_LISTENPORT`, value: `SSHWIFTY_ENV_RENAMED:PORT`. This will tell Sshwifty to read port number from environment variable `PORT` which is imposed by Heroku runtime.

**Comment by nullifye** [comment]
Walla. successfully deploy this repo using docker image.

You have done a great project.

**Comment by niruix** [comment]
Glad you like it :)
